language: node_js
node_js:
- '4.0'
before_script:
- npm install
script:
- npm test
env:
  matrix:
    secure: fZ7O7rczilUun9/zV3l4d0xW2m0Mg7cVFr3+bdrW687yUIBVJSqbrexMHwKhbrPb1i8ZsQ0pvSLzWbGE8qJI65s6z0zR5Zp/cKexV4uXgROXgInYVKVyTZOFG34BidNMhsY4aRYsmDaQsr53fpAs806ijSMeQgDyDzVJmJvNnMw9UY2z5M1Kn7cIyLBphHqyLckXY6WeBlq2Oa9xGyG+dqhJ8/vsGGupECwmJhWC60Vvub52g/t9CEFATyzjbiQp8T38HkJlaL2ZkDqa0HtbvbCBdDSa/SOA/nnRqZwSekdfYH9+n9cNuinUBJELybo/bf3cU9AOogUyofip18pKlWUGSODLavfi28LP1pWObmAPp262JNUPen+fcbWgpwygtGchRG986ntgC0/r7eK4nlc/ZSyPyDcIYs2AfkIO9C7k58cq2YdjIZ1FOL0bZvqMjR+kMReJ70S7R5ZG0KS12ehcd/KI3kAJ4v1O3MIgnXEwnCFvHqW7QVeqoJCuM5UXDwUpb9Z614YB3MpxX5RnonR/S2sRjnEuenZlZY3uinyr5N4w5/LRheT05k10M/Qj1/90Gu/64CXsk8VXW90uZtNbcChkspJtsmRrGpxaiznCdywYC97j5dmsh0T0fouHC/os/Qhr1HeTGXrbCXyvUY4SO1dSXVFPrqpbLk5dHPg=
